# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClipPic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClipPic
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'GoogleSignIn'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'MJRefresh'

  target 'ClipPicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClipPicUITests' do
    # Pods for testing
  end

end
